name: ts_interop
description: Creates Dart interop types for JavaScript based on TypeScript declaration files.
version: 0.1.0
repository: https://github.com/blimster/ts_interop

environment:
  sdk: ^3.5.0

dependencies:
  binary_tree: ^1.0.6
  code_builder: ^4.10.0
  dart_style: ^2.3.6
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
